name: Fetch Holidays Yearly

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set Dynamic Matrix (Persian Calendar)
        id: set-matrix
        run: |
          CURRENT_YEAR=$(date +"%Y")
          SHAMSI_YEAR=$((CURRENT_YEAR - 621))
          YEARS=$(seq $SHAMSI_YEAR $((SHAMSI_YEAR + 5)))
          echo "matrix=$(echo $YEARS | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT

  fetch-holidays:
    needs: scrape
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: ${{ fromJson(needs.scrape.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install puppeteer

      - name: Run Scraper for ${{ matrix.year }}
        run: node index.js ${{ matrix.year }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

      - name: Commit and Push changes
        run: |
          git add holidays/
          git diff --cached --quiet || (git commit -m "[UPDATE] Holidays for ${{ matrix.year }}" && git push origin HEAD:main)
      


