name: Fetch Holidays Yearly

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set Dynamic Matrix (Persian Calendar)
        id: set-matrix
        run: |
          CURRENT_YEAR=$(date +"%Y")
          SHAMSI_YEAR=$((CURRENT_YEAR - 621))
          YEARS=$(seq $SHAMSI_YEAR $((SHAMSI_YEAR + 5)))
          echo "matrix=$(echo $YEARS | jq -R -s -c 'split(" ")')" >> $GITHUB_OUTPUT

  fetch-holidays:
    needs: scrape
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year: ${{ fromJson(needs.scrape.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install puppeteer

      - name: Run Scraper for ${{ matrix.year }}
        run: node index.js ${{ matrix.year }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          message: "[UPDATE] Holidays for ${{ matrix.year }}"


